---
    version: '3'

    services:
      python:
        image: python:3
        working_dir: /code
        ports:
          - "9000:9000"
        volumes:
          - ./code:/code
        entrypoint: ["./run.sh"]
    
